extends: "airbnb-base"
plugins:
    - "import"
env:
    browser: true
    webextensions: true
rules:
    no-use-before-define: 0
    no-fallthrough: 0
    no-param-reassign: 0
    import/prefer-default-export: 0
    no-underscore-dangle: 0
    no-unused-vars:
        - error:
            argsIgnorePattern: "^_"
    ignore-rest-siblings: 0
overrides:
    - files:
        - src/**/*.spec.js
      env:
        mocha: true
      globals:
        expect: false
      rules:
        prefer-arrow-callback: 0
        func-names: 0
        prefer-template: 0
        no-plusplus: 0
